#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import re
import glob

def translate_arabic_content():
    # Comprehensive Arabic to English translation dictionary
    translations = {
        # Navigation and Menu Items
        "الصفحة الرئيسية": "Home",
        "حولنا": "About Us", 
        "حول الشركة": "About Company",
        "بروفايل الشركة": "Company Profile",
        "تاريخنا": "Our History",
        "رسالة القائد": "Leader's Message",
        "رؤيتنا ومهمتنا وقيمنا": "Our Vision, Mission & Values",
        "الرسالة والرؤية والقيم": "Mission, Vision & Values",
        "الكفاءة العملية": "Operational Excellence",
        "إستراتيجيتنا": "Our Strategy",
        "الاستراتيجية": "Strategy",
        "خدماتنا": "Our Services",
        "الخدمات": "Services",
        "الخدمات الثقيلة": "Hard Services",
        "الخدمات الصعبة": "Hard Services",
        "الخدمات الخفيفة": "Soft Services", 
        "الخدمات اللينة": "Soft Services",
        "الخدمات المتخصصة": "Specialist Services",
        "التخصصات": "Specializations",
        "البنية التحتية": "Infrastructure",
        "القطاعات": "Sectors",
        "قطاعات": "Sectors",
        "الأخبار والفعاليات": "News & Events",
        "أخبار وأحداث": "News & Events",
        "شهادات العملاء": "Testimonials",
        "الشهادات": "Testimonials",
        "آراء العملاء": "Client Testimonials",
        "المسؤولية الاجتماعية للشركات": "Corporate Social Responsibility",
        "وظائف": "Careers",
        "تواصل معنا": "Get in Touch",
        "اطلب عرض سعر": "Request a Quote",
        "أطلب الأسعار": "Request Pricing",
        "من نحن": "About Us",
        " من نحن   ": "About Us",
        
        # Page Titles and Meta Content
        "وظائف - Mozoon": "Careers - Mozoon",
        "بروفايل الشركة - Mozoon": "Company Profile - Mozoon",
        "تاريخنا - Mozoon": "Our History - Mozoon",
        "رسالة القائد - Mozoon": "Leader's Message - Mozoon",
        "الكفاءة العملية - Mozoon": "Operational Excellence - Mozoon",
        "المسؤولية الاجتماعية للشركات - Mozoon": "Corporate Social Responsibility - Mozoon",
        "قطاعات - Mozoon": "Sectors - Mozoon",
        
        # Address and Contact Information
        "المملكة العربية السعودية": "Kingdom of Saudi Arabia",
        "الرياض": "Riyadh",
        "العليا": "Olaya",
        "طريق الملك فهد": "King Fahd Road",
        "المملكة العربية السعودية - الرياض - العليا - طريق الملك فهد": "Kingdom of Saudi Arabia - Riyadh - Olaya - King Fahd Road",
        "مكتب رقم 11-109, مبنى مكين.": "Office No. 11-109, Makeen Building.",
        "طريق المطار, دبي": "Airport Road, Dubai",
        
        # Footer and Copyright
        "جميع الحقوق محفوظة": "All Rights Reserved",
        "حقوق الطبع والنشر © 2025 جميع الحقوق محفوظة ،  مجموعة مزون الخير": "Copyright © 2025 All Rights Reserved, Mozoon Al Khair Group",
        " حقوق الطبع والنشر © 2025 جميع الحقوق محفوظة ،  مجموعة مزون الخير ": "Copyright © 2025 All Rights Reserved, Mozoon Al Khair Group",
        
        # Email and Contact
        "البريد الإلكتروني": "Email",
        "للاستفسارات": "For Inquiries",
        "راسلنا على": "Contact us at",
        "راسلنا عبر البريد الالكتروني": "Contact us via Email",
        "اتصل بنا": "Contact Us",
        "ساعات العمل": "Working Hours",
        "ايام العمل من الاحد الي الخميس من ٨ الي ٤ م ماعدا السبت من ١ ظهرا الي ٤ م": "Working days from Sunday to Thursday from 8 AM to 4 PM except Saturday from 1 PM to 4 PM",
        " العنوان": "Address",
        
        # Company Profile Content
        "بروفايل شركة مزون الخير": "Mozoon Al Khair Company Profile",
        "مرحباً بكم في عالم المستقبل المستدام مع مجموعة مزون الخير": "Welcome to the world of sustainable future with Mozoon Al Khair Group",
        "نظرة عامة عن الشركة": "Company Overview",
        "في مجموعة مزون الخير، نحن لا نبني ونحافظ فقط على المرافق ولكننا نفي بوعدنا من خلالها. نحن متخصصون في تقديم حلول مخصصة وفريدة للمرافق التجارية والسكنية والصناعية والمستشفيات والمنشآت التعليمية.": "At Mozoon Al Khair Group, we don't just build and maintain facilities, but we fulfill our promise through them. We specialize in providing customized and unique solutions for commercial, residential, industrial, hospital and educational facilities.",
        "نحن نقدم خدمات إدارة المرافق والتوظيف على مستوى عالمي ونحرص على أن تكون قيمة مضافة لعملائنا، كذلك نحن نستثمر في موظفينا وفي المرافق وفي التقنيات وفي الوعي بالسوق.": "We provide facility management and recruitment services at a global level and ensure that they are added value to our clients. We also invest in our employees, facilities, technologies and market awareness.",
        "قصتنا": "Our Story",
        "تأسست مجموعة مزون الخير بهدف تقديم خدمات متميزة في مجال إدارة المرافق والخدمات المتكاملة. منذ انطلاقتنا، كنا نؤمن بأن النجاح الحقيقي يكمن في تقديم حلول مبتكرة تلبي احتياجات عملائنا وتتجاوز توقعاتهم.": "Mozoon Al Khair Group was established with the aim of providing distinguished services in the field of facility management and integrated services. Since our launch, we have believed that true success lies in providing innovative solutions that meet our clients' needs and exceed their expectations.",
        "نحن نفخر بكوننا شركة سعودية تساهم في تحقيق رؤية المملكة 2030 من خلال تقديم خدمات عالية الجودة تدعم التنمية المستدامة والنمو الاقتصادي.": "We are proud to be a Saudi company that contributes to achieving the Kingdom's Vision 2030 by providing high-quality services that support sustainable development and economic growth.",
        "قيمنا الأساسية": "Our Core Values",
        "التميز": "Excellence",
        "نسعى دائماً لتحقيق أعلى معايير الجودة والتميز في جميع خدماتنا": "We always strive to achieve the highest standards of quality and excellence in all our services",
        "الثقة": "Trust",
        "نبني علاقات طويلة الأمد مع عملائنا قائمة على الثقة والشفافية": "We build long-term relationships with our clients based on trust and transparency",
        "الابتكار": "Innovation",
        "نستخدم أحدث التقنيات والحلول المبتكرة لتطوير خدماتنا باستمرار": "We use the latest technologies and innovative solutions to continuously develop our services",
        "فريق العمل": "Our Team",
        "يضم فريق عمل مزون الخير نخبة من المتخصصين والخبراء في مختلف المجالات، من مهندسين وفنيين ومديري مشاريع، جميعهم يعملون بروح الفريق الواحد لتحقيق أهداف الشركة وتقديم أفضل الخدمات لعملائنا.": "Mozoon Al Khair's team includes a select group of specialists and experts in various fields, from engineers, technicians and project managers, all working as one team to achieve the company's goals and provide the best services to our clients.",
        "نحن نؤمن بأن الاستثمار في الموارد البشرية هو أساس نجاح أي مؤسسة، لذلك نحرص على تطوير قدرات فريقنا من خلال برامج التدريب المستمر والتطوير المهني.": "We believe that investing in human resources is the foundation of any institution's success, so we are keen to develop our team's capabilities through continuous training and professional development programs.",
        "التزامنا تجاه عملائنا": "Our Commitment to Our Clients",
        "نلتزم بتقديم خدمات عالية الجودة تلبي احتياجات عملائنا وتساهم في نجاح أعمالهم. نحن نؤمن بأن رضا العميل هو مقياس نجاحنا الحقيقي، ونعمل جاهدين لتحقيق هذا الهدف من خلال الالتزام بالمواعيد، والجودة العالية، والخدمة المتميزة.": "We are committed to providing high-quality services that meet our clients' needs and contribute to their business success. We believe that customer satisfaction is the measure of our true success, and we work hard to achieve this goal through commitment to deadlines, high quality, and distinguished service.",
        
        # News and Events Content
        "الأخبار والأحداث": "News & Events",
        "تابع آخر أخبار وأحداث شركة مزون الخير، إنجازاتنا الحديثة، وأحدث التطورات في مجال الخدمات المتكاملة.": "Follow the latest news and events of Mozoon Al Khair Company, our recent achievements, and the latest developments in integrated services.",
        "مركز الأخبار": "News Center",
        "أحدث الأخبار • الفعاليات القادمة • الإنجازات الحديثة • التطورات المؤسسية": "Latest News • Upcoming Events • Recent Achievements • Institutional Developments",
        "أخبار حديثة": "Recent News",
        "فعاليات مميزة": "Distinguished Events",
        "إنجازات متميزة": "Outstanding Achievements",
        "آخر الأخبار": "Latest News",
        "توقيع عقد جديد": "New Contract Signing",
        "جديد": "New",
        "أخبار الشركة": "Company News",
        "توقيع عقد خدمات متكاملة مع مجمع طبي كبير": "Signing an integrated services contract with a major medical complex",
        "وقعت شركة مزون الخير عقداً استراتيجياً لتقديم خدمات النظافة والصيانة والأمن لأحد أكبر المجمعات الطبية في المملكة، مما يعزز من مكانتها في القطاع الصحي.": "Mozoon Al Khair Company signed a strategic contract to provide cleaning, maintenance and security services to one of the largest medical complexes in the Kingdom, enhancing its position in the healthcare sector.",
        "اقرأ المزيد ←": "Read More ←",
        "جائزة التميز": "Excellence Award",
        "إنجاز": "Achievement",
        "جوائز وتكريم": "Awards and Recognition",
        "حصول الشركة على جائزة التميز في الخدمات المتكاملة": "Company receives Excellence Award in Integrated Services",
        "تم تكريم شركة مزون الخير بجائزة التميز في الخدمات المتكاملة من قبل غرفة التجارة، تقديراً لجودة خدماتها والتزامها بأعلى معايير الجودة والسلامة.": "Mozoon Al Khair Company was honored with the Excellence Award in Integrated Services by the Chamber of Commerce, in recognition of the quality of its services and commitment to the highest standards of quality and safety.",
        "تدشين فرع جديد": "Opening a New Branch",
        "توسع": "Expansion",
        "التوسع": "Expansion",
        "تدشين فرع جديد في المنطقة الشرقية": "Opening a new branch in the Eastern Region",
        "افتتحت شركة مزون الخير فرعاً جديداً في الدمام لتوسيع نطاق خدماتها في المنطقة الشرقية، مما يعكس نمو الشركة المستمر واستراتيجيتها التوسعية.": "Mozoon Al Khair Company opened a new branch in Dammam to expand its services in the Eastern Region, reflecting the company's continuous growth and expansion strategy.",
        "شراكة استراتيجية": "Strategic Partnership",
        "شراكة": "Partnership",
        "شراكات": "Partnerships",
        "شراكة استراتيجية مع شركة تقنية رائدة": "Strategic partnership with a leading technology company",
        "أعلنت مزون الخير عن شراكة استراتيجية مع إحدى الشركات التقنية الرائدة لتطوير حلول ذكية ومبتكرة في مجال إدارة المرافق والخدمات المتكاملة.": "Mozoon Al Khair announced a strategic partnership with one of the leading technology companies to develop smart and innovative solutions in facility management and integrated services.",
        "الفعاليات القادمة": "Upcoming Events",
        "يناير": "January",
        "معرض الخدمات": "Services Exhibition",
        "معرض الخدمات المتكاملة 2025": "Integrated Services Exhibition 2025",
        "مشاركة الشركة في معرض الخدمات المتكاملة بالرياض لعرض أحدث الحلول والتقنيات": "Company participation in the Integrated Services Exhibition in Riyadh to showcase the latest solutions and technologies",
        "مركز الرياض الدولي للمؤتمرات": "Riyadh International Convention Center",
        "فبراير": "February",
        "ورشة تدريبية": "Training Workshop",
        "ورشة تدريبية للموظفين": "Employee Training Workshop",
        "ورشة تدريبية متخصصة في أحدث تقنيات النظافة والصيانة لتطوير مهارات الفريق": "Specialized training workshop on the latest cleaning and maintenance techniques to develop team skills",
        "مقر الشركة الرئيسي": "Company Headquarters",
        "مارس": "March",
        "مؤتمر الاستدامة": "Sustainability Conference",
        "مؤتمر الاستدامة البيئية": "Environmental Sustainability Conference",
        "مشاركة في مؤتمر الاستدامة البيئية لعرض مبادرات الشركة الخضراء": "Participation in the Environmental Sustainability Conference to showcase the company's green initiatives",
        "فندق الريتز كارلتون": "Ritz Carlton Hotel",
        "إنجازات الشركة": "Company Achievements",
        "سنة من التميز": "Year of Excellence",
        "مشروع منجز": "Completed Project",
        
        # Leaders Message Content - Additional Mixed Content
        "كلمة من قيادة Mozoon Al Khair Group": "Message from Mozoon Al Khair Group Leadership",
        "كلمة من قيادة": "Message from Leadership",
        "تاريخ Mozoon Al Khair Group": "Mozoon Al Khair Group History",
        "رحلة من النجاح والAchievementات عبر السنين": "A journey of success and achievements over the years",
        "بداية الرحلة": "The Beginning of the Journey",
        "بدأت قصة Mozoon Al Khair Group من رؤية طموحة لتقديم خدمات متميزة في مجال إدارة المرافق وServices المتكاملة. منذ اللحظة الأولى، كان هدفنا واضحاً: أن نكون الشريك الموثوق للشركات والمؤسسات في تحقيق أهدافها التشغيلية.": "The story of Mozoon Al Khair Group began with an ambitious vision to provide distinguished services in facility management and integrated services. From the first moment, our goal was clear: to be the trusted partner for companies and institutions in achieving their operational goals.",
        "مع مرور السنوات، نمت الشركة وتطورت لتصبح واحدة من الشركات الرائدة في Kingdom of Saudi Arabia، مع فريق عمل متخصص وخبرات متراكمة تمتد لأكثر من عقد من الزمن.": "Over the years, the company grew and developed to become one of the leading companies in the Kingdom of Saudi Arabia, with a specialized team and accumulated experience spanning more than a decade.",
        "المحطات المهمة في Our History": "Important Milestones in Our History",
        "التأسيس والانطلاقة": "Foundation and Launch",
        "تأسست Mozoon Al Khair Group بهدف تقديم خدمات إدارة المرافق المتخصصة، مع التركيز على الجودة وExcellence في الخدمة.": "Mozoon Al Khair Group was established with the aim of providing specialized facility management services, focusing on quality and excellence in service.",
        "الExpansion الأول": "First Expansion",
        "Expansionت الشركة لتشمل خدمات Newة وفتحت فروعاً إضافية، مما مكنها من خدمة عدد أكبر من العملاء في مختلف المناطق.": "The company expanded to include new services and opened additional branches, enabling it to serve a larger number of clients in different regions.",
        "الحصول على Testimonials": "Obtaining Certifications",
        "حصلت الشركة على شهادات الجودة العالمية ISO وشهادات السلامة المهنية، مما عزز من مكانتها في السوق.": "The company obtained international quality certifications ISO and occupational safety certificates, which enhanced its position in the market.",
        "التحول الرقمي": "Digital Transformation",
        "استثمرت الشركة في التقنيات الحديثة وأنظمة إدارة المرافق الذكية، مما حسن من كفاءة Services المقدمة.": "The company invested in modern technologies and smart facility management systems, which improved the efficiency of services provided.",
        "الريادة وExcellence": "Leadership and Excellence",
        "اليوم، تقف Mozoon Al Khair Group كواحدة من الشركات الرائدة في المملكة، مع فريق يضم أكثر من 1000 موظف متخصص.": "Today, Mozoon Al Khair Group stands as one of the leading companies in the Kingdom, with a team of more than 1000 specialized employees.",
        "Achievementاتنا عبر السنين": "Our Achievements Over the Years",
        "Completed Projects بنجاح": "Successfully Completed Projects",
        "جائزة وشهادة تقدير": "Awards and Certificates of Appreciation",
        "موظف متخصص": "Specialized Employee",
        "إرثنا وتراثنا": "Our Legacy and Heritage",
        "على مدار أكثر من 15 عاماً، بنت Mozoon Al Khair Group سمعة قوية في السوق السعودي كشركة موثوقة ومبتكرة. نحن نفخر بالإرث الذي بنيناه وTrust التي وضعها عملاؤنا فينا.": "Over more than 15 years, Mozoon Al Khair Group has built a strong reputation in the Saudi market as a reliable and innovative company. We are proud of the legacy we have built and the trust our clients have placed in us.",
        "كل مشروع نفذناه وكل عميل خدمناه ساهم في تشكيل هويتنا وتعزيز مكانتنا كرواد في مجال إدارة المرافق. نحن نحمل هذا الإرث بفخر ونتطلع لمستقبل أكثر إشراقاً.": "Every project we executed and every client we served contributed to shaping our identity and strengthening our position as leaders in facility management. We carry this legacy with pride and look forward to a brighter future.",
        "Our Core Values منذ البداية:": "Our Core Values Since the Beginning:",
        "Commitment to Quality العالية": "Commitment to High Quality",
        "الشفافية في التعامل": "Transparency in Dealing",
        "Innovation المستمر": "Continuous Innovation",
        "المسؤولية الاجتماعية": "Social Responsibility",
        "نحو المستقبل": "Towards the Future",
        "بينما نحتفل بAchievementاتنا الماضية، نتطلع بثقة نحو المستقبل. نحن ملتزمون بمواصلة رحلة Excellence وInnovation، ونسعى لأن نكون جزءاً من تحقيق رؤية المملكة 2030 من خلال تقديم خدمات عالمية المستوى تساهم في التنمية المستدامة.": "While we celebrate our past achievements, we look forward with confidence to the future. We are committed to continuing the journey of excellence and innovation, and we strive to be part of achieving the Kingdom's Vision 2030 by providing world-class services that contribute to sustainable development.",
        "رؤيتنا": "Our Vision",
        "أن نكون الخيار الأول في المنطقة": "To be the first choice in the region",
        "مهمتنا": "Our Mission",
        "تقديم حلول مبتكرة ومستدامة": "Providing innovative and sustainable solutions",
        "هدفنا": "Our Goal",
        "تحقيق Excellence في كل ما نقوم به": "Achieving excellence in everything we do",
        "كن جزءاً من قصة نجاحنا": "Be part of our success story",
        "انضم إلى مئات العملاء الذين وثقوا بنا على مدار السنين": "Join hundreds of clients who have trusted us over the years",
        "ابدأ رحلتك معنا": "Start your journey with us",
        "تعرف علينا أكثر": "Learn more about us",
        
        # Operational Excellence Content - Additional Mixed Content
        "نحن نسعى لتحقيق أعلى مستويات Operational Excellence من خلال تطبيق أفضل المMarchات والمعايير الدولية في جميع عملياتنا وOur Services.": "We strive to achieve the highest levels of Operational Excellence by applying the best practices and international standards in all our operations and services.",
        "ركائز Operational Excellence": "Pillars of Operational Excellence",
        "تطبيق أنظمة Quality Management المعتمدة دولياً لضمان تقديم خدمات تفوق توقعات العملاء.": "Implementing internationally accredited Quality Management systems to ensure delivering services that exceed customer expectations.",
        "Innovation التقني": "Technical Innovation",
        "استخدام أحدث التقنيات والأدوات المتطورة لتعزيز كفاءة العمليات وجودة Services.": "Using the latest technologies and advanced tools to enhance operational efficiency and service quality.",
        "إطار عمل Operational Excellence": "Operational Excellence Framework",
        "تحديد أهداف واضحة وقابلة للقياس لتحقيق Excellence العملي.": "Setting clear and measurable goals to achieve operational excellence.",
        "نظام Quality Management المعتمد دولياً لضمان Continuous Improvement.": "Internationally accredited Quality Management system to ensure Continuous Improvement.",
        "نسبة Services المنجزة وفقاً للمعايير المطلوبة": "Percentage of services completed according to required standards",
        "معدل Customer Satisfaction عن Our Services": "Customer Satisfaction rate for Our Services",
        "رحلة Excellence العملي": "Operational Excellence Journey",
        "تطبيق الحلول والمMarchات الNewة": "Implementing new solutions and practices",
        "متابعة النتائج وContinuous Improvement": "Monitoring results and Continuous Improvement",
        "نستخدم أحدث التقنيات والأنظمة الذكية لتعزيز كفاءة عملياتنا وتحسين جودة Our Services بشكل مستمر.": "We use the latest technologies and smart systems to enhance the efficiency of our operations and continuously improve the quality of our services.",
        "اكتشف Excellence معنا": "Discover Excellence with us",
        "انضم إلى رحلة Operational Excellence واكتشف كيف يمكن لOur Services المتميزة أن تحقق أهدافك بأعلى مستويات الجودة والكفاءة.": "Join the Operational Excellence journey and discover how our distinguished services can achieve your goals with the highest levels of quality and efficiency.",
        
        # CSR Content - Additional Mixed Content
        "نؤمن بدورنا الحيوي في خدمة المجتمع والمساهمة في التنمية المستدامة، من خلال برامج ومبادرات تهدف إلى إحداث تأثير إيجابي في حياة الناس والبيئة.": "We believe in our vital role in serving the community and contributing to sustainable development, through programs and initiatives aimed at creating a positive impact on people's lives and the environment.",
        "رؤيتنا في المسؤولية الاجتماعية": "Our Vision in Social Responsibility",
        "أن نكون شركة رائدة في المسؤولية الاجتماعية، نساهم في بناء مجتمع مستدام ومزدهر للأجيال القادمة.": "To be a leading company in social responsibility, contributing to building a sustainable and prosperous society for future generations.",
        "الاستدامة": "Sustainability",
        "الPartnership": "Partnership",
        "ركائز المسؤولية الاجتماعية": "Pillars of Social Responsibility",
        "البيئة والاستدامة": "Environment and Sustainability",
        "حماية البيئة والموارد الطبيعية": "Protecting the environment and natural resources",
        "برامج إعادة التدوير والتقليل من النفايات": "Recycling programs and waste reduction",
        "استخدام الطاقة المتجددة والتقنيات الخضراء": "Using renewable energy and green technologies",
        "حماية الموارد المائية والطبيعية": "Protecting water and natural resources",
        "تقليل البصمة الكربونية للشركة": "Reducing the company's carbon footprint",
        "المجتمع المحلي": "Local Community",
        "دعم وتنمية المجتمعات المحلية": "Supporting and developing local communities",
        "برامج التعليم والتدريب المهني": "Education and vocational training programs",
        "دعم المشاريع الصغيرة والمتوسطة": "Supporting small and medium enterprises",
        "المساهمة في الأعمال الخيرية والإنسانية": "Contributing to charitable and humanitarian work",
        "تطوير Infrastructure المجتمعية": "Developing community infrastructure",
        "الموظفون": "Employees",
        "رعاية وتطوير رأس المال البشري": "Caring for and developing human capital",
        "برامج التطوير المهني والتدريب المستمر": "Professional development and continuous training programs",
        "بيئة عمل آمنة وصحية": "Safe and healthy work environment",
        "برامج الرعاية الصحية والاجتماعية": "Healthcare and social care programs",
        "تحقيق التوازن بين العمل والحياة": "Achieving work-life balance",
        "الحوكمة الأخلاقية": "Ethical Governance",
        "Transparency and Integrity في الأعمال": "Transparency and Integrity in Business",
        "تطبيق أعلى معايير Transparency and Integrity": "Applying the highest standards of Transparency and Integrity",
        "مكافحة الفساد والمMarchات غير الأخلاقية": "Fighting corruption and unethical practices",
        "احترام حقوق الإنسان والعدالة": "Respecting human rights and justice",
        "الامتثال للقوانين والمعايير الدولية": "Compliance with laws and international standards",
        "برامجنا ومبادراتنا": "Our Programs and Initiatives",
        "Education Program والتدريب": "Education and Training Program",
        "نوفر برامج تعليمية وتدريبية متخصصة لتطوير المهارات وبناء القدرات في المجتمع.": "We provide specialized educational and training programs to develop skills and build capabilities in the community.",
        "برنامج حماية البيئة": "Environmental Protection Program",
        "مبادرات شاملة لحماية البيئة والحفاظ على الموارد الطبيعية للأجيال القادمة.": "Comprehensive initiatives to protect the environment and preserve natural resources for future generations.",
        "Health Program المجتمعية": "Community Health Program",
        "حملات توعوية وخدمات صحية مجانية لتحسين الصحة العامة في المجتمع.": "Awareness campaigns and free health services to improve public health in the community.",
        "تأثيرنا الإيجابي": "Our Positive Impact",
        "المستفيدون": "Beneficiaries",
        "من برامجنا التعليمية والتدريبية": "From our educational and training programs",
        "المشاريع": "Projects",
        "البيئية والاجتماعية المنجزة": "Environmental and social projects completed",
        "تقليل الانبعاثات": "Emission Reduction",
        "في البصمة الكربونية للشركة": "In the company's carbon footprint",
        "الامتثال": "Compliance",
        "للمعايير الأخلاقية والقانونية": "To ethical and legal standards",
        "Partnershipsنا Strategy": "Our Partnership Strategy",
        "نتعاون مع منظمات محلية ودولية لتحقيق أهدافنا في المسؤولية الاجتماعية وتوسيع نطاق تأثيرنا الإيجابي.": "We collaborate with local and international organizations to achieve our social responsibility goals and expand the scope of our positive impact.",
        "🏛️ المؤسسات الحكومية": "🏛️ Government Institutions",
        "Partnerships مع الجهات الحكومية لتنفيذ مشاريع التنمية المستدامة.": "Partnerships with government agencies to implement sustainable development projects.",
        "🏫 المؤسسات التعليمية": "🏫 Educational Institutions",
        
        # Soft Services Content - Additional Mixed Content
        "نقدم مجموعة متكاملة من Soft Specialist Services التي تركز على الجانب الإنساني والإداري، مما يضمن بيئة عمل مريحة ومنتجة لعملائنا.": "We provide a comprehensive range of Soft Specialist Services that focus on the human and administrative aspect, ensuring a comfortable and productive work environment for our clients.",
        "مجالات Soft Services": "Soft Services Areas",
        "خدمات الاستقبال • إدارة المكاتب • الدعم الإداري • خدمات العملاء • التدريب والتطوير • الاستشارات الإدارية": "Reception services • Office management • Administrative support • Customer services • Training and development • Management consulting",
        "خدمات الاستقبال": "Reception Services",
        "إدارة المكاتب": "Office Management",
        "التدريب والتطوير": "Training and Development",
        "استقبال احترافي ومتميز للزوار": "Professional and distinguished reception for visitors",
        "استقبال الزوار والعملاء بطريقة Professionalism": "Receiving visitors and clients in a professional manner",
        "إدارة المواعيد والحجوزات": "Managing appointments and reservations",
        "تقديم المعلومات والإرشادات": "Providing information and guidance",
        "التعامل مع الاستفسارات الهاتفية": "Handling phone inquiries",
        "إدارة البريد والمراسلات": "Managing mail and correspondence",
        "إدارة شاملة للعمليات المكتبية": "Comprehensive management of office operations",
        "تنظيم وإدارة الملفات والوثائق": "Organizing and managing files and documents",
        "إدارة المخزون والمستلزمات المكتبية": "Managing inventory and office supplies",
        "تنسيق الاجتماعات والفعاليات": "Coordinating meetings and events",
        "إعداد التقارير والعروض التقديمية": "Preparing reports and presentations",
        "إدارة قواعد البيانات والأرشيف": "Managing databases and archives",
        "الدعم الإداري": "Administrative Support",
        "دعم إداري متكامل للشركات": "Comprehensive administrative support for companies",
        "دعم العمليات الإدارية اليومية": "Supporting daily administrative operations",
        "إدارة Human Resources والرواتب": "Managing Human Resources and payroll",
        "متابعة Projects والمهام": "Following up on projects and tasks",
        "إعداد الميزانيات والتقارير المالية": "Preparing budgets and financial reports",
        "Development السياسات والإجراءات": "Developing policies and procedures",
        "خدمات العملاء": "Customer Services",
        "Service عملاء متميزة ومتخصصة": "Distinguished and specialized customer service",
        "الرد على استفسارات العملاء": "Responding to customer inquiries",
        "معالجة الشكاوى والمقترحات": "Handling complaints and suggestions",
        "متابعة Customer Satisfaction": "Following up on Customer Satisfaction",
        "تقديم الدعم الفني والإرشاد": "Providing technical support and guidance",
        "إدارة علاقات العملاء (CRM)": "Customer Relationship Management (CRM)",
        "برامج تدريبية متخصصة لتطوير مهارات الموظفين وزيادة الإنتاجية.": "Specialized training programs to develop employee skills and increase productivity.",
        "برامج التدريب المهني والتقني": "Professional and technical training programs",
        "Development المهارات القيادية": "Developing leadership skills",
        "ورش العمل التخصصية": "Specialized workshops",
        "التدريب على التقنيات الحديثة": "Training on modern technologies",
        "الاستشارات الإدارية": "Management Consulting",
        "استشارات إدارية متخصصة لتحسين الأداء وتطوير العمليات.": "Specialized management consulting to improve performance and develop operations.",
        "تحليل وتطوير العمليات": "Process analysis and development",
        "استشارات الإدارة Strategy": "Strategic management consulting",
        "تحسين الهيكل التنظيمي": "Improving organizational structure",
        "Development أنظمة الجودة": "Developing quality systems",
        "فوائد Soft Services": "Benefits of Soft Services",
        "تساعد Soft Services في تحسين بيئة العمل وزيادة الإنتاجية من خلال التركيز على الجانب الإنساني والإداري.": "Soft Services help improve the work environment and increase productivity by focusing on the human and administrative aspect.",
        "📈 زيادة الإنتاجية": "📈 Increasing Productivity",
        "تحسين كفاءة العمليات الإدارية والتشغيلية.": "Improving the efficiency of administrative and operational processes.",
        "😊 تحسين بيئة العمل": "😊 Improving Work Environment",
        "خلق بيئة عمل إيجابية ومحفزة للموظفين.": "Creating a positive and motivating work environment for employees.",
        "💰 توفير التكاليف": "💰 Cost Savings",
        "تقليل التكاليف التشغيلية وتحسين العائد على الاستثمار.": "Reducing operational costs and improving return on investment.",
        "مميزات Our Soft Services": "Features of Our Soft Services",
        "Team مؤهل": "Qualified Team",
        "Team عمل مدرب ومؤهل بأعلى المعايير المهنية": "Trained and qualified work team with the highest professional standards",
        "Solutions مخصصة": "Customized Solutions",
        "Solutions مصممة خصيصاً لتلبية احتياجات كل Client": "Solutions designed specifically to meet each client's needs",
        "مراقبة الأداء": "Performance Monitoring",
        "نظام متقدم لمراقبة وتقييم الأداء المستمر": "Advanced system for monitoring and evaluating continuous performance",
        "تحسين مستمر": "Continuous Improvement",
        "التطوير وContinuous Improvement للخدمات والعمليات": "Development and Continuous Improvement of services and operations",
        "منهجية العمل": "Work Methodology",
        "التحليل والتقييم": "Analysis and Evaluation",
        "دراسة شاملة لاحتياجات العميل وCurrent Status": "Comprehensive study of client needs and current status",
        "وضع خطة عمل مفصلة وتصميم الحلول المناسبة": "Developing a detailed work plan and designing appropriate solutions",
        "تطبيق الحلول وتنفيذ Services بأعلى Quality": "Implementing solutions and executing services with the highest quality",
        "المتابعة والتطوير": "Follow-up and Development",
        "مراقبة الأداء وContinuous Development للخدمات": "Performance monitoring and continuous development of services",
        "استفد من Our Soft Services المتميزة": "Benefit from Our Distinguished Soft Services",
        "Get In Touch اليوم لتحسين بيئة العمل وزيادة الإنتاجية من خلال Our Soft Specialist Services.": "Get In Touch today to improve the work environment and increase productivity through our Soft Specialist Services.",
        "طلب عرض سعر": "Request a Quote",
        
        # Image Paths and Alt Text
        "alt=\"Innovation التقني\"": "alt=\"Technical Innovation\"",
        "alt=\"بداية الشركة\"": "alt=\"Company Beginning\"",
        "alt=\"تأسيس الشركة\"": "alt=\"Company Foundation\"",
        "alt=\"الExpansion الأول\"": "alt=\"First Expansion\"",
        "alt=\"التحول الرقمي\"": "alt=\"Digital Transformation\"",
        "alt=\"الوضع الحالي\"": "alt=\"Current Status\"",
        "alt=\"إرث الشركة\"": "alt=\"Company Legacy\"",
        "alt=\"البيئة والاستدامة\"": "alt=\"Environment and Sustainability\"",
        "alt=\"المجتمع المحلي\"": "alt=\"Local Community\"",
        "alt=\"الموظفون\"": "alt=\"Employees\"",
        "alt=\"الحوكمة الأخلاقية\"": "alt=\"Ethical Governance\"",
        "alt=\"خدمات الاستقبال\"": "alt=\"Reception Services\"",
        "alt=\"إدارة المكاتب\"": "alt=\"Office Management\"",
        "alt=\"الدعم الإداري\"": "alt=\"Administrative Support\"",
        "alt=\"خدمات العملاء\"": "alt=\"Customer Services\"",
        "alt=\"التدريب والتطوير\"": "alt=\"Training and Development\"",
        "alt=\"الاستشارات الإدارية\"": "alt=\"Management Consulting\"",
        "alt=\"فوائد Soft Services\"": "alt=\"Benefits of Soft Services\"",
        "جائزة وتكريم": "Award and Recognition",
        "حصول على شهادة الآيزو الجديدة": "Obtaining the new ISO certificate",
        "حصلت الشركة على شهادة الآيزو 45001 لأنظمة إدارة السلامة والصحة المهنية، مما يؤكد التزامها بأعلى معايير السلامة.": "The company obtained ISO 45001 certificate for occupational health and safety management systems, confirming its commitment to the highest safety standards.",
        "نوفمبر": "November",
        "إنجاز مشروع ضخم": "Completing a Major Project",
        "إنجاز مشروع ضخم في وقت قياسي": "Completing a major project in record time",
        "نجحت الشركة في إنجاز مشروع خدمات متكاملة لمجمع تجاري كبير في الرياض خلال 6 أشهر فقط، متفوقة على الجدول الزمني المحدد.": "The company successfully completed an integrated services project for a large commercial complex in Riyadh in just 6 months, exceeding the specified timeline.",
        "أكتوبر": "October",
        "التغطية الإعلامية": "Media Coverage",
        
        # Leaders Message Content
        "كلمة من قيادة مجموعة مزون الخير": "Message from Mozoon Al Khair Group Leadership",
        "قائد الشركة": "Company Leader",
        "المهندس أحمد مزون": "Engineer Ahmed Mozoon",
        "الرئيس التنفيذي والمؤسس": "CEO and Founder",
        "رؤيتنا للمستقبل": "Our Vision for the Future",
        "في مجموعة مزون الخير، نؤمن بأن النجاح الحقيقي يكمن في تقديم خدمات تتجاوز توقعات عملائنا وتساهم في بناء مستقبل مستدام لمجتمعنا": "At Mozoon Al Khair Group, we believe that true success lies in providing services that exceed our clients' expectations and contribute to building a sustainable future for our community",
        "رسالة من القيادة": "Message from Leadership",
        "أعزائي الشركاء والعملاء الكرام،": "Dear Partners and Valued Clients,",
        "يسعدني أن أرحب بكم في موقع مجموعة مزون الخير، الشركة الرائدة في مجال إدارة المرافق والخدمات المتكاملة في المملكة العربية السعودية. منذ تأسيس الشركة، كان هدفنا الأساسي هو تقديم خدمات عالية الجودة تلبي احتياجات عملائنا وتساهم في تحقيق أهدافهم التجارية والتشغيلية.": "I am pleased to welcome you to the Mozoon Al Khair Group website, the leading company in facility management and integrated services in the Kingdom of Saudi Arabia. Since the company's establishment, our primary goal has been to provide high-quality services that meet our clients' needs and contribute to achieving their business and operational objectives.",
        "نحن نؤمن بأن النجاح الحقيقي يأتي من خلال الالتزام بالتميز في كل ما نقوم به. لذلك، نحرص على الاستثمار في أحدث التقنيات وأفضل الممارسات العالمية، بالإضافة إلى تطوير قدرات فريقنا المتخصص لدينا بشكل مستمر.": "We believe that true success comes through commitment to excellence in everything we do. Therefore, we are keen to invest in the latest technologies and best global practices, in addition to continuously developing the capabilities of our specialized team.",
        "إن رؤية المملكة 2030 تلهمنا يومياً لنكون جزءاً من التحول الاقتصادي والاجتماعي الذي تشهده بلادنا الحبيبة. نحن ملتزمون بتقديم حلول مبتكرة ومستدامة تساهم في تحقيق هذه الرؤية الطموحة وتدعم النمو الاقتصادي للمملكة.": "The Kingdom's Vision 2030 inspires us daily to be part of the economic and social transformation that our beloved country is witnessing. We are committed to providing innovative and sustainable solutions that contribute to achieving this ambitious vision and support the Kingdom's economic growth.",
        "في مجموعة مزون الخير، نعتبر كل عميل شريكاً في النجاح، ونسعى جاهدين لبناء علاقات طويلة الأمد قائمة على الثقة والشفافية والجودة العالية. فريقنا المتخصص يعمل على مدار الساعة لضمان تقديم أفضل الخدمات وأكثرها فعالية.": "At Mozoon Al Khair Group, we consider every client a partner in success, and we strive to build long-term relationships based on trust, transparency and high quality. Our specialized team works around the clock to ensure the delivery of the best and most effective services.",
        "كما نؤمن بمسؤوليتنا الاجتماعية تجاه المجتمع، ونحرص على المساهمة في التنمية المستدامة من خلال برامج المسؤولية الاجتماعية والمبادرات البيئية التي نطلقها بانتظام.": "We also believe in our social responsibility towards the community, and we are keen to contribute to sustainable development through social responsibility programs and environmental initiatives that we launch regularly.",
        "أتطلع إلى مواصلة رحلة النجاح معكم، وأعدكم بأن نبقى دائماً في المقدمة، نقدم لكم أفضل ما لدينا من خبرات وخدمات تساهم في تحقيق أهدافكم وطموحاتكم.": "I look forward to continuing the journey of success with you, and I promise you that we will always remain at the forefront, providing you with the best of our expertise and services that contribute to achieving your goals and aspirations.",
        "المهندس أحمد مزون": "Engineer Ahmed Mozoon",
        "الرئيس التنفيذي والمؤسس - مجموعة مزون الخير": "CEO and Founder - Mozoon Al Khair Group",
        "مبادئ القيادة لدينا": "Our Leadership Principles",
        "الرؤية الواضحة": "Clear Vision",
        "نحدد أهدافنا بوضوح ونعمل بخطة استراتيجية محكمة لتحقيقها": "We define our goals clearly and work with a solid strategic plan to achieve them",
        "القيادة بالقدوة": "Leading by Example",
        "نقود فريقنا بالمثال الإيجابي ونلهمهم لتحقيق أفضل النتائج": "We lead our team by positive example and inspire them to achieve the best results",
        "التطوير المستمر": "Continuous Development",
        "نسعى للتحسين المستمر في جميع جوانب عملنا وخدماتنا": "We strive for continuous improvement in all aspects of our work and services",
        "قيمنا في العمل": "Our Work Values",
        "الالتزام بالجودة": "Commitment to Quality",
        "نضع معايير الجودة العالية في مقدمة أولوياتنا ونحرص على تطبيقها في كل مشروع": "We put high quality standards at the top of our priorities and ensure their application in every project",
        "الشفافية والنزاهة": "Transparency and Integrity",
        "نتعامل مع عملائنا وشركائنا بصدق وشفافية تامة في جميع المعاملات": "We deal with our clients and partners with honesty and complete transparency in all transactions",
        "الابتكار والتطوير": "Innovation and Development",
        "نستثمر في التقنيات الحديثة ونطور حلولاً مبتكرة تلبي احتياجات السوق": "We invest in modern technologies and develop innovative solutions that meet market needs",
        "قيم الشركة": "Company Values",
        "رؤيتنا للمستقبل": "Our Vision for the Future",
        "نتطلع إلى أن نكون الشركة الرائدة في مجال إدارة المرافق على مستوى المنطقة، ونساهم في تحقيق رؤية المملكة 2030 من خلال تقديم خدمات مبتكرة ومستدامة تدعم التنمية الاقتصادية والاجتماعية": "We aspire to be the leading company in facility management at the regional level, and contribute to achieving the Kingdom's Vision 2030 by providing innovative and sustainable services that support economic and social development",
        "توسيع نطاق خدماتنا": "Expanding our services",
        "الريادة الإقليمية": "Regional Leadership",
        "التميز العالمي": "Global Excellence",
        "نتطلع للعمل معكم": "We look forward to working with you",
        "نحن هنا لنكون شريككم في النجاح ونساعدكم في تحقيق أهدافكم": "We are here to be your partner in success and help you achieve your goals",
        
        # Operational Excellence Content
        "نحن نسعى لتحقيق أعلى مستويات التميز العملي من خلال تطبيق أفضل الممارسات والمعايير الدولية في جميع عملياتنا وخدماتنا.": "We strive to achieve the highest levels of operational excellence by applying best practices and international standards in all our operations and services.",
        "ركائز التميز العملي": "Pillars of Operational Excellence",
        "تطبيق أنظمة إدارة الجودة المعتمدة دولياً لضمان تقديم خدمات تفوق توقعات العملاء.": "Implementing internationally accredited quality management systems to ensure delivering services that exceed customer expectations.",
        "الابتكار التقني": "Technical Innovation",
        "استخدام أحدث التقنيات والأدوات المتطورة لتعزيز كفاءة العمليات وجودة الخدمات.": "Using the latest technologies and advanced tools to enhance operational efficiency and service quality.",
        "إطار عمل التميز العملي": "Operational Excellence Framework",
        "تحديد أهداف واضحة وقابلة للقياس لتحقيق التميز العملي.": "Setting clear and measurable goals to achieve operational excellence.",
        "نظام إدارة الجودة المعتمد دولياً لضمان التحسين المستمر.": "Internationally accredited quality management system to ensure continuous improvement.",
        "نسبة الخدمات المنجزة وفقاً للمعايير المطلوبة": "Percentage of services completed according to required standards",
        "معدل رضا العملاء عن خدماتنا": "Customer satisfaction rate for our services",
        "رحلة التميز العملي": "Operational Excellence Journey",
        "التقييم الأولي": "Initial Assessment",
        "تحليل الوضع الحالي وتحديد نقاط التحسين": "Analyzing the current situation and identifying improvement points",
        "التخطيط والتصميم": "Planning and Design",
        "وضع خطة شاملة للتطوير والتحسين": "Developing a comprehensive plan for development and improvement",
        "التنفيذ والتطبيق": "Implementation and Application",
        "تطبيق الحلول والممارسات الجديدة": "Implementing new solutions and practices",
        "المراقبة والتحسين": "Monitoring and Improvement",
        "متابعة النتائج والتحسين المستمر": "Following up on results and continuous improvement",
        "التكامل التقني": "Technical Integration",
        "نستخدم أحدث التقنيات والأنظمة الذكية لتعزيز كفاءة عملياتنا وتحسين جودة خدماتنا بشكل مستمر.": "We use the latest technologies and smart systems to enhance the efficiency of our operations and continuously improve the quality of our services.",
        "الذكاء الاصطناعي": "Artificial Intelligence",
        "تحليل البيانات": "Data Analysis",
        "الحوسبة السحابية": "Cloud Computing",
        "التطبيقات الذكية": "Smart Applications",
        "اكتشف التميز معنا": "Discover Excellence with Us",
        "انضم إلى رحلة التميز العملي واكتشف كيف يمكن لخدماتنا المتميزة أن تحقق أهدافك بأعلى مستويات الجودة والكفاءة.": "Join the operational excellence journey and discover how our distinguished services can achieve your goals with the highest levels of quality and efficiency.",
        "احصل على عرض سعر": "Get a Quote",
        
        # CSR Content
        "برنامج التعليم": "Education Program",
        "برنامج البيئة": "Environment Program",
        "برنامج الصحة": "Health Program",
        
        # Mixed Content from Search Results
        "Services الصعبة": "Hard Services",
        "Services اللينة": "Soft Services",
        "Services الثقيلة": "Hard Services",
        "Services الخفيفة": "Soft Services",
        "Services المتخصصة": "Specialist Services",
        " حقوق الطبع والنشر © 2025 All Rights Reserved ،  Mozoon Al Khair Group ": "Copyright © 2025 All Rights Reserved, Mozoon Al Khair Group",
        "Services - Mozoon": "Services - Mozoon",
        "مرحبًا بكم في عالم المستقبل المستدام .. في Mozoon Al Khair Group، نحن لا نبني ونحافظ فقط على المرافق ولكننا نفي بوعدنا من خلالها، نحن متخصصون في تقديم حلول مخصصة وفريدة للمرافق التجارية والسكنية والصناعية والمستشفيات والمنشآت التعليمية، We provide facility management and recruitment services at a global level and ensure that they are added value to our clients. We also invest in our employees, facilities, technologies and market awareness.": "Welcome to the world of sustainable future. At Mozoon Al Khair Group, we don't just build and maintain facilities, but we fulfill our promise through them. We specialize in providing customized and unique solutions for commercial, residential, industrial, hospital and educational facilities. We provide facility management and recruitment services at a global level and ensure that they are added value to our clients. We also invest in our employees, facilities, technologies and market awareness.",
        
        # Additional mixed content
        "تأسست Mozoon Al Khair Group بهدف تقديم خدمات متميزة في مجال إدارة المرافق وServices المتكاملة. منذ انطلاقتنا، كنا نؤمن بأن النجاح الحقيقي يكمن في تقديم حلول مبتكرة تلبي احتياجات عملائنا وتتجاوز توقعاتهم.": "Mozoon Al Khair Group was established with the aim of providing distinguished services in the field of facility management and integrated services. Since our launch, we have believed that true success lies in providing innovative solutions that meet our clients' needs and exceed their expectations.",
        "تاريخ الشركة": "Company History",
        "نسعى دائماً لتحقيق أعلى معايير الجودة وExcellence في جميع Our Services": "We always strive to achieve the highest standards of quality and excellence in all our services",
        "نبني علاقات طويلة الأمد مع عملائنا قائمة على Trust والشفافية": "We build long-term relationships with our clients based on trust and transparency",
        "نستخدم أحدث التقنيات والحلول المبتكرة لتطوير Our Services باستمرار": "We use the latest technologies and innovative solutions to continuously develop our services",
        "يضم فريق عمل مزون الخير نخبة منSpecialists والخبراء في مختلف المجالات، من مهندسين وفنيين ومديري مشاريع، جميعهم يعملون بروح الفريق الواحد لتحقيق أهداف الشركة وتقديم أفضل Services لعملائنا.": "Mozoon Al Khair's team includes a select group of specialists and experts in various fields, from engineers, technicians and project managers, all working as one team to achieve the company's goals and provide the best services to our clients.",
        "Get in Touch الآن": "Get in Touch Now",
        
        # Image paths and alt text
        "Mozoon Al Khair Company Images": "mozoon-company-images",
        "إنجازاتنا بالأرقام": "Our Achievements in Numbers",
        "مشروع مكتمل": "Completed Projects",
        "عميل راضٍ": "Satisfied Clients",
        "سنة خبرة": "Years of Experience",
        "افضل الموظفين": "Best Employees",
        " المتخصصين": "Specialists",
        "معرض الصور": "Photo Gallery",
        "مشاريع الشركة": "Company Projects",
        "خدمات الشركة": "Company Services",
        "فريق العمل": "Our Team",
        "هل تريد معرفة المزيد عنا؟": "Want to know more about us?",
        "نحن هنا للإجابة على جميع استفساراتكم وتقديم الاستشارات المجانية": "We are here to answer all your inquiries and provide free consultations",
        "تواصل معنا الآن": "Contact us now",
        "نظرة عامة": "Overview",
        "مرحبًا بكم في عالم المستقبل المستدام .. في مجموعة مزون الخير، نحن لا نبني ونحافظ فقط على المرافق ولكننا نفي بوعدنا من خلالها، نحن متخصصون في تقديم حلول مخصصة وفريدة للمرافق التجارية والسكنية والصناعية والمستشفيات والمنشآت التعليمية، نحن نقدم خدمات إدارة المرافق والتوظيف على مستوى عالمي ونحرص على أن تكون قيمة مضافة لعملائنا، كذلك نحن نستثمر في موظفينا وفي المرافق وفي التقنيات وفي الوعي بالسوق.": "Welcome to the world of sustainable future .. At Mozoon Al Khair Group, we don't just build and maintain facilities, but we fulfill our promise through them. We specialize in providing customized and unique solutions for commercial, residential, industrial, hospital and educational facilities. We provide facility management and recruitment services at a global level and ensure that they are added value to our clients. We also invest in our employees, facilities, technologies and market awareness.",
        " المزيد من المعلومات ": "More Information",
        "حولنا ": "About Us",
        "بروفايل الشركة": "Company Profile",
        "رسالة المدير العام": "CEO Message",
        " روابط سريعة ": "Quick Links",
        " معلومات التواصل ": "Contact Information",
        
        # Operational Excellence Content
        "ركائز الكفاءة العملية": "Pillars of Operational Excellence",
        "إدارة الجودة": "Quality Management",
        "تطبيق أنظمة إدارة الجودة المعتمدة دولياً لضمان تقديم خدمات تفوق توقعات العملاء.": "Implementing internationally certified quality management systems to ensure delivering services that exceed customer expectations.",
        "التحسين المستمر": "Continuous Improvement",
        "تطوير وتحسين العمليات بشكل مستمر لتحقيق أعلى مستويات الكفاءة والفعالية.": "Continuously developing and improving processes to achieve the highest levels of efficiency and effectiveness.",
        "الابتكار التقني": "Technical Innovation",
        "استخدام أحدث التقنيات والأدوات المتطورة لتعزيز كفاءة العمليات وجودة الخدمات.": "Using the latest technologies and advanced tools to enhance process efficiency and service quality.",
        "الموارد البشرية": "Human Resources",
        "تطوير قدرات الفريق وتدريبه المستمر لضمان تقديم أفضل مستويات الخدمة.": "Developing team capabilities and continuous training to ensure delivering the best service levels.",
        "إطار عمل الكفاءة العملية": "Operational Excellence Framework",
        "التخطيط الاستراتيجي": "Strategic Planning",
        "📋 تحليل الاحتياجات": "📋 Needs Analysis",
        "دراسة شاملة لمتطلبات العملاء والسوق لتحديد أولويات التطوير.": "Comprehensive study of customer and market requirements to determine development priorities.",
        "🎯 وضع الأهداف": "🎯 Goal Setting",
        "تحديد أهداف واضحة وقابلة للقياس لتحقيق التميز العملي.": "Setting clear and measurable goals to achieve operational excellence.",
        "📊 مؤشرات الأداء": "📊 Performance Indicators",
        "وضع مؤشرات أداء رئيسية لمراقبة وقياس مستوى التقدم.": "Setting key performance indicators to monitor and measure progress levels.",
        "التنفيذ والمراقبة": "Implementation and Monitoring",
        "⚡ التنفيذ السريع": "⚡ Rapid Implementation",
        "تطبيق الخطط والاستراتيجيات بكفاءة عالية وفي الوقت المحدد.": "Implementing plans and strategies with high efficiency and on time.",
        "📈 المراقبة المستمرة": "📈 Continuous Monitoring",
        "متابعة دقيقة لجميع العمليات لضمان الجودة والكفاءة.": "Precise monitoring of all processes to ensure quality and efficiency.",
        "🔄 التطوير المستمر": "🔄 Continuous Development",
        "تحسين العمليات باستمرار بناءً على النتائج والتغذية الراجعة.": "Continuously improving processes based on results and feedback.",
        "معايير الجودة والاعتمادات": "Quality Standards and Certifications",
        "نظام إدارة الجودة المعتمد دولياً لضمان التحسين المستمر.": "Internationally certified quality management system to ensure continuous improvement.",
        "نظام إدارة الصحة والسلامة المهنية لحماية العاملين.": "Occupational health and safety management system to protect workers.",
        "نظام الإدارة البيئية للحفاظ على البيئة والاستدامة.": "Environmental management system to preserve the environment and sustainability.",
        "نظام إدارة أمن المعلومات لحماية البيانات والمعلومات.": "Information security management system to protect data and information.",
        "مؤشرات الأداء الرئيسية": "Key Performance Indicators",
        "معدل الجودة": "Quality Rate",
        "نسبة الخدمات المنجزة وفقاً للمعايير المطلوبة": "Percentage of services completed according to required standards",
        "الاستجابة": "Response",
        "خدمة عملاء متاحة على مدار الساعة": "24/7 customer service available",
        "رضا العملاء": "Customer Satisfaction",
        "معدل رضا العملاء عن خدماتنا": "Customer satisfaction rate with our services",
        "الحوادث": "Incidents",
        "هدفنا صفر حوادث في مكان العمل": "Our goal is zero workplace incidents",
        "رحلة التميز العملي": "Operational Excellence Journey",
        "نحن نسعى لتحقيق أعلى مستويات الكفاءة العملية من خلال تطبيق أفضل الممارسات والمعايير الدولية في جميع عملياتنا وخدماتنا.": "We strive to achieve the highest levels of operational efficiency by applying best practices and international standards in all our operations and services.",
        
        # History Page Mixed Content
        "بدأت قصة Mozoon Al Khair Company من رؤية طموحة لتقديم خدمات متميزة في مجال إدارة المرافق وServices المتكاملة. منذ اللحظة الأولى، كان Our Goal واضحاً: أن نكون الشريك الموثوق للشركات والمؤسسات في تحقيق أهدافها التشغيلية.": "The story of Mozoon Al Khair Company began with an ambitious vision to provide distinguished services in the field of facility management and integrated services. From the first moment, our goal was clear: to be the trusted partner for companies and institutions in achieving their operational goals.",
        
        # Image Paths
        "صور شركة مزون الخير": "mozoon-company-images",
        
        # Additional Mixed Content
        "مجموعة مزون الخير": "Mozoon Al Khair Group",
        "شركة مزون الخير": "Mozoon Al Khair Company",
    }
    
    # Find all English HTML files (including backup files)
    english_files = []
    
    # Primary English files
    for file in glob.glob("/Users/ibrahimfakhry/Desktop/new/*-en.html"):
        english_files.append(file)
    
    # Backup English files
    for file in glob.glob("/Users/ibrahimfakhry/Desktop/new/*-en.html.backup"):
        english_files.append(file)
    
    # Backup directory English files
    for file in glob.glob("/Users/ibrahimfakhry/Desktop/new/backup_en_files/*-en.html"):
        english_files.append(file)
    
    translated_count = 0
    
    for file_path in english_files:
        try:
            # Read the file
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            original_content = content
            
            # Apply translations
            for arabic_text, english_text in translations.items():
                if arabic_text in content:
                    content = content.replace(arabic_text, english_text)
            
            # Only write if content changed
            if content != original_content:
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(content)
                translated_count += 1
                print(f"Translated: {os.path.basename(file_path)}")
        
        except Exception as e:
            print(f"Error processing {file_path}: {e}")
    
    print(f"\nTranslation completed! Translated {translated_count} files successfully.")

if __name__ == "__main__":
    translate_arabic_content()